"""Add last_seen_place to missing_persons

Revision ID: 50259e0e085b
Revises: 7b7ad1981c11
Create Date: 2025-06-12 23:57:47.605337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50259e0e085b'
down_revision = '7b7ad1981c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missing_persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen_place', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missing_persons', schema=None) as batch_op:
        batch_op.drop_column('last_seen_place')

    # ### end Alembic commands ###
