"""Add location and description to ImageRecord

Revision ID: 795a8ee612ab
Revises: 
Create Date: 2025-06-02 11:53:45.427684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795a8ee612ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('image_records', sa.Column('last_seen_place', sa.String(length=255), nullable=True))




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('predicted_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='image_records_pkey')
    )
    # ### end Alembic commands ###
