"""Add reported_by to MissingPerson

Revision ID: 7b7ad1981c11
Revises: b98fc1707895
Create Date: 2025-06-12 19:50:16.998415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b7ad1981c11'
down_revision = 'b98fc1707895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reported_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['reported_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reported_by')

    # ### end Alembic commands ###
